services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: amt_crm_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - amt_crm_network

networks:
  amt_crm_network:
    driver: bridge
